### ISSUE TITLE
ConnectParams should be using the 6_5_0 struct on >= 6.5.0?

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/ffi-vix_disk_lib#19]
The ConnectParams are setup with a hardocded value of 6.5.0 in order to add an extra field on that version.  However, 6.7.0 is not using that extended version.  Should it?  If so, is this a bug?

**Comment by Fryguy** [comment]
@agrare @jerryk55 ?

**Comment by jerryk55** [comment]
This looks to be a "bug" in that if any of the functions requiring ConnectParams are called using VixDiskLib 6.7.0 they would be missing the extended value - vimApiVer - in the structure. I  It should probably use the 6.5.0 ConnectParams with a version of 6.5.0 *or greater*.  Its not clear to me that *we* ever set that value anywhere.  I don't see it in the VMwareWebService/VixDiskLib code that uses ffi-vix_disk_lib.

**Comment by Fryguy** [comment]
Ok, that was my thought as well, so I think this is a bug.
